## Don't touch this if you running under Docker container
listen = "0.0.0.0:6665"

## Don't touch if you don't know what you're doing
# token = "<random symbols>"

## Path to minecraft server folder
## Sculptor try to use ban list from it
# mcFolder = "~/minecraft_server"

## Can't work without at least one provider!
## If not set, default providers (Mojang, ElyBy) will be provided.
# authProviders = [
#     { name = "Mojang", url = "https://sessionserver.mojang.com/session/minecraft/hasJoined" },
#     { name = "ElyBy", url = "https://account.ely.by/api/minecraft/session/hasJoined" },
# ]

## Enabling Asset Updater.
## If false, Sculptor will still respond to assets. Sculptor will handle any installed assets.
## (The path must be ./data/assets unless overridden!)
## This allows you to modify or create your own assets from scratch. X>
## Default value = false
assetsUpdaterEnabled = true

## Message of The Day
## It will be displayed to every player in the Figura menu who is connected to your server
[motd]
displayServerInfo = true
sInfoUptime = "Uptime: "
sInfoAuthClients = "Authenticated clients: " 
sInfoDrawIndent = true
customText = """
[
    {
        "text": "You are connected to "
    },
    {
        "color": "gold",
        "text": "The Sculptor"
    },
    {
        "text": "\\nUnofficial Backend V2 for Figura\\n\\n"
    },
    {
        "clickEvent": {
            "action": "open_url",
            "value": "https://github.com/shiroyashik/sculptor"
        },
        "text": "Please "
    },
    {
        "clickEvent": {
            "action": "open_url",
            "value": "https://github.com/shiroyashik/sculptor"
        },
        "color": "gold",
        "text": "Star",
        "underlined": true
    },
    {
        "clickEvent": {
            "action": "open_url",
            "value": "https://github.com/shiroyashik/sculptor"
        },
        "text": " me on GitHub!\\n\\n"
    }
]
"""

## Full update of these parameters occurs only after restarting the Sculptor!!!
[limitations]
maxAvatarSize = 100 # KB
maxAvatars = 10 # It doesn't look like Figura has any actions implemented with this?
# P.S. And it doesn't look like the current API allows anything like that...

[advancedUsers.66004548-4de5-49de-bade-9c3933d8eb97]
username = "Shiroyashik"
special = [0,0,0,1,0,0] # 6
pride = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] # 25

## With advancedUsers you can set additional parameters
# [advancedUsers.your-uuid-here]
# username = "Your_username_here"
# banned = true
# special = [0,1,0,0,0,0] # Set badges what you want! :D
# pride = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] # Check out note.txt for reference

## you can create an unlimited number of "advancedUsers" for any players.